require 'rules/avoid_keyword'
require 'rules/method_indentation'
require 'rules/instance_variable_limit'
require 'rules/avoid_accessor'
require 'rules/class_line_limit'
require 'rules/method_chaining_limit'
